name: Publish to NPM

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '.github/**'
      - '.husky/**'

jobs:
  publish:
    name: Build, Verify, and Publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      packages: write
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          # This makes sure the entire history is fetched, which is required for changesets to work properly
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
      
      - name: Setup PNPM
        uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: false
      
      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      
      - name: Install Dependencies
        run: pnpm install
      
      - name: Lint
        run: pnpm lint
      
      - name: Clean
        run: pnpm clean
      
      - name: Build
        run: pnpm build
      
      - name: Verify Build
        run: pnpm verify
      
      - name: Create Release Pull Request or Publish to NPM
        id: changesets
        uses: changesets/action@v1
        with:
          # This expects you to have a script called release which runs changeset publish
          publish: pnpm release
          version: pnpm version-packages
          commit: "chore: version packages"
          title: "chore: version packages"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      - name: Publish (if not already published by changesets)
        if: steps.changesets.outputs.published != 'true'
        run: |
          # Only run if there are no unpublished changesets and we're on main
          if [ -z "$(ls -A .changeset)" ] || [ "$(ls -A .changeset | grep -v 'README.md\|config.json')" = "" ]; then
            echo "No changesets found, checking if we need to publish current version"
            
            # Check if the current version is published
            PKG_NAME=$(node -p "require('./package.json').name")
            PKG_VERSION=$(node -p "require('./package.json').version")
            
            HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" "https://registry.npmjs.org/$PKG_NAME/$PKG_VERSION")
            
            if [ "$HTTP_STATUS" = "404" ]; then
              echo "Version $PKG_VERSION not found on NPM. Publishing..."
              npm publish --access public
            else
              echo "Version $PKG_VERSION already published. Skipping."
            fi
          else
            echo "Changesets found but not processed. This might require manual attention."
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} 